baseURL = 'https://induvarshini.github.io/'
languageCode = 'en-us'
title = 'Personal Home of Indu'
theme = "paper"

disqusShortname = 'Indu'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  linkedin = 'induvarshini'             # linkedin.com/in/YOUR_LINKEDIN_ID
  github = 'InduVarshini'                 # github.com/YOUR_GITHUB_ID
  instagram = 'justonelifeitis'           # instagram.com/YOUR_INSTAGRAM_ID
  

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Indu Varshini'
